#!/bin/sh

DAEMON="dns320l-daemon"

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -S -x "/usr/bin/$DAEMON"
	status="$?"
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -s INT -K -x "/usr/bin/$DAEMON"
}

poweroff() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -s TERM -K -x "/usr/bin/$DAEMON"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|poweroff}"
		exit 1
		;;
esac
