#!/bin/sh

trap "" HUP
trap "" TERM

start() {
	printf "Starting Simple System Daemon for D-Link DNS-320L: "
	/usr/bin/dns320l-daemon
	if [ $? != 0 ]; then
		echo "FAILED"
		exit 1
	else
		echo "done"
	fi
}

stop() {
	printf "Stopping Simple System Daemon for D-Link DNS-320L: "
	killall dns320l-daemon
        echo "done"
}

case "$1" in
    start)
	start
	;;

    stop)
	stop
	;;

    restart)
    	stop
    	start
	;;

    *)
	echo "Usage: /etc/init.d/S50dns320l-daemon {start|stop|restart}"
	exit 1
	;;
esac

exit 0
