################################################################################
#
# iniparser
#
################################################################################

INIPARSER_VERSION = 4.1
INIPARSER_SITE = $(call github,ndevilla,iniparser,v$(INIPARSER_VERSION))
INIPARSER_INSTALL_STAGING = YES
INIPARSER_LICENSE = MIT
INIPARSER_LICENSE_FILES = LICENSE
INIPARSER_SO_TARGET = libiniparser.so.1
INIPARSER_A_TARGET = libiniparser.a
INIPARSER_BUILD_TARGETS =
INIPARSER_STAGING_INSTALL_TGTS =
INIPARSER_TARGET_INSTALL_TGTS =

INIPARSER_CONFIGURE_OPTS = $(TARGET_CONFIGURE_OPTS)

ifeq ($(BR2_STATIC_LIBS),y)
INIPARSER_BUILD_TARGETS = $(INIPARSER_A_TARGET)
INIPARSER_STAGING_INSTALL_TGTS = $(INIPARSER_A_TARGET)
INIPARSER_TARGET_INSTALL_TGTS = $(INIPARSER_A_TARGET)
else ifeq ($(BR2_SHARED_LIBS),y)
INIPARSER_LINK_SO = y

INIPARSER_BUILD_TARGETS = $(INIPARSER_SO_TARGET)
INIPARSER_STAGING_INSTALL_TGTS = $(INIPARSER_SO_TARGET)

INIPARSER_TARGET_INSTALL_TGTS = $(INIPARSER_SO_TARGET)
else ifeq ($(BR2_SHARED_STATIC_LIBS),y)
INIPARSER_LINK_SO = y

INIPARSER_BUILD_TARGETS = $(INIPARSER_A_TARGET) $(INIPARSER_SO_TARGET)
INIPARSER_STAGING_INSTALL_TGTS = $(INIPARSER_A_TARGET) $(INIPARSER_SO_TARGET)

# Don't install static libs on target
INIPARSER_TARGET_INSTALL_TGTS = $(INIPARSER_SO_TARGET)
endif

define INIPARSER_BUILD_CMDS
	$(INIPARSER_CONFIGURE_OPTS) $(TARGET_MAKE_ENV) $(MAKE) -C $(@D) $(INIPARSER_BUILD_TARGETS)
endef

define INIPARSER_INSTALL_STAGING_CMDS
	$(INSTALL) -D -m 0644 $(@D)/src/iniparser.h $(@D)/src/dictionary.h $(STAGING_DIR)/usr/include/
	$(foreach target,$(INIPARSER_STAGING_INSTALL_TGTS),$(INSTALL) -D -m 0755 $(@D)/$(target) $(STAGING_DIR)/usr/lib/)
	$(if $(INIPARSER_LINK_SO),ln -s -r $(STAGING_DIR)/usr/lib/$(INIPARSER_SO_TARGET) $(STAGING_DIR)/usr/lib/libiniparser.so)
endef

define INIPARSER_INSTALL_TARGET_CMDS
	$(foreach target,$(INIPARSER_TARGET_INSTALL_TGTS),$(INSTALL) -D -m 0755 $(@D)/$(target) $(TARGET_DIR)/usr/lib/)
	$(if $(INIPARSER_LINK_SO),ln -s -r $(TARGET_DIR)/usr/lib/$(INIPARSER_SO_TARGET) $(TARGET_DIR)/usr/lib/libiniparser.so)
endef

$(eval $(generic-package))
